homeassistant:
  customize:
    automation.bedroom_charging_evening_on:
      friendly_name: 'Automation: Start bedroome charger'
    automation.charger_off_controller:
      friendly_name: 'Automation: Turn off charger in livingroom'
    automation.evening_light_on:
      friendly_name: 'Automation: Evening light'
    automation.evening_light_off:
      friendly_name: 'Automation: Turn off evening light'
    automation.turnofftv:
      friendly_name: 'Automation: Turn off TV when no motion detected'
    automation.winter_element_workroom:
      friendly_name: 'Automation: Start element in workroom'
    automation.winter_element_workroom_off:
      friendly_name: 'Automation: Turn off element in workroom'
    automation.turnonkitchen:
      friendly_name: 'Automation: Diskbänksbelysning'
    automation.morning_light_on:
      friendly_name: 'Automation: Morning light'
    automation.morninglight_off:
      friendly_name: 'Automation: Morning light off'
    automation.charger_workroom_off:
      friendly_name: 'Automation: Workroom charger'
    switch.kok_fonsterlampa:
      friendly_name: 'Förrådsbelysning'
    light.koksbank:
      friendly_name: Diskbänksbelysning
    switch.hall_trapplampa:
      friendly_name: Trapplampa
    switch.altan_belysning:
      friendly_name: Belysning
    sensor.hall_rorelsesensor_temperature:
      friendly_name: Temperatur
    sensor.hall_rorelsesensor_luminance:
      friendly_name: Luminans
    sensor.kok_rorelsesensor_temperature:
      friendly_name: Temperatur
    sensor.kok_rorelsesensor_luminance:
      friendly_name: Luminans
    sensor.barnrum_temperature_2:
      friendly_name: Temperatur
    sensor.barnrum_humidity_2:
      friendly_name: Fuktkvot
    switch.vardagsrum_bordslampa:
      friendly_name: Bordslampa
    switch.laddare_vardagsrum:
      friendly_name: Laddare
    switch.vardagsrum_fonsterlampa:
      friendly_name: Fönsterlampa
    camera.livingroom:
      friendly_name: Övervakningskamera
    sensor.laddare_vardagsrum_power_2:
      friendly_name: Laddare
    sensor.vardagsrum_rorelsesensor_temperature:
      friendly_name: Temperatur
    sensor.vardagsrum_rorelsesensor_luminance:
      friendly_name: Luminans
    light.korridor_fonsterlampa:
      friendly_name: Fönsterlampa
    sensor.sovrum_humidity_2:
      friendly_name: Fuktkvot
    sensor.sovrum_temperature_2:
      friendly_name: Temeperatur
    switch.syrum_fonsterlampa:
      friendly_name: Fönsterlampa
    sensor.utomhus_humidity:
      friendly_name: Fuktkvot
    sensor.utomhus_temperature:
      friendly_name: Temperatur
    switch.forrad_uttag:
      friendly_name: Uttag
    sensor.forrad_uttag_power_2:
      friendly_name: Energi
    sensor.forrad_humidity:
      friendly_name: Fuktkvot
    sensor.forrad_temperature:
      friendly_name: Temperatur
    sensor.forradsfrys_temperatur:
      friendly_name: Frys temperatur



  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.154
        - 192.168.0.6
        - 192.168.0.14

      allow_bypass_login: true
    - type: homeassistant



  whitelist_external_dirs:
   - '/tmp'
# Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises d
  latitude: 56.1616
  longitude: 15.5866
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 17
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: 
    homed:
        primary-color: "#dee2e3"
        accent-color: "#a3a3a3"
        dark-primary-color: "##979999"
        light-primary-color: "var(--accent-color)"
        primary-text-color: "#0d0d0d"
        text-primary-color: "var(--primary-text-color)"
        secondary-text-color: "#0d0d0d"
        disabled-text-color: "#7a7a7a"
        label-badge-border-color: "#dee2e3"
        primary-background-color: "#dee2e3"
        secondary-background-color: "#dee2e3"
        divider-color: "rgba(0, 0, 0, .12)"
        table-row-background-color: "#dee2e3"
        table-row-alternative-background-color: "#dee2e3"
        paper-listbox-color: "var(--primary-color)"
        paper-listbox-background-color: "var(--accent-color)"
        paper-grey-50: "var(--primary-text-color)"
        paper-grey-200: "var(--accent-color)"
        paper-card-header-color: "var(--dark-primary-color)"
        paper-card-background-color: "var(--accent-color)"
        paper-dialog-background-color: "#dee2e3"
        paper-item-icon-color: "var(--primary-text-color)"
        paper-item-icon-active-color: "#9c3535"
        paper-item-icon_-_color: "black"
        paper-item-selected_-_color: "var(--accent-color)"
        paper-item-selected_-_background-color: "#9c3535"
        paper-tabs-selection-bar-color: "green"
        label-badge-red: "#9c3535"
        label-badge-text-color: "var(--primary-text-color)"
        label-badge-background-color: "var(--accent-color)"
        paper-toggle-button-checked-button-color: "9c3535"
        paper-toggle-button-checked-bar-color: "var(--primary-color)"
        paper-toggle-button-checked-ink-color: "#9c3535"
        paper-toggle-button-unchecked-button-color: "var(--secondary-background-color)"
        paper-toggle-button-unchecked-bar-color: "var(--secondary-text-color)"
        paper-toggle-button-unchecked-ink-color: "var(--secondary-background-color)"
        paper-slider-knob-color: "var(--secondary-text-color)"
        paper-slider-knob-start-color: "var(--secondary-text-color)"
        paper-slider-pin-color: "var(--secondary-text-color)"
        paper-slider-active-color: "var(--secondary-text-color)"
        paper-slider-container-color: "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat"
        paper-slider-secondary-color: "var(--secondary-background-color)"
        paper-slider-disabled-active-color: "var(--disabled-text-color)"
        paper-slider-disabled-secondary-color: "var(--disabled-text-color)"
        google-red-500: "#9c3535"
        google-green-500: "#9c3535"
# javascript_version: es5

 
# Example configuration.yaml entry
alarm_control_panel: 
  - platform: manual
    name: alarm
    code: !secret alarm_code
    pending_time: 450
    delay_time: 60
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

config:
http:
  # Uncomment this to add a password (recommended!)
  # api_password: 
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123switch
device_tracker:
  - platform: ping
    hosts:
     kristian: !secret k_ip
     dorothea: !secret d_ip
    consider_home: 00:30:00
    track_new_devices: yes
  #- platform: owntracks
  - platform: mqtt
    devices:
      user:
        'owntracks/user/device'
owntracks:
  max_gps_accuracy: 200

camera:
    - platform: mjpeg
      name: livingroom
      mjpeg_url: !secret cam_l_ip
      username: !secret cam_l_user
      password: !secret cam_l_pass

updater:

telegram_bot:
 - platform: polling
   api_key: !secret tel_api_key
   allowed_chat_ids:
    - 631406925
    - 579904946


# Discover some devices automatically
#discovery:


conversation:
# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
 include:
  domains:
   automation
 exclude:
  domains:
   script


yeelight:
  devices:
    192.168.0.8:
       name: Altan
       transition: 1000
      
    

# Track the sun
sun:


weather:
  - platform: yweather


notify:
  - name: pushb_k
    platform: telegram
    chat_id: !secret k_t_id
  - name: pushb_d
    platform: telegram
    chat_id: !secret d_t_id
 
group: !include groups.yaml

input_select:
     hus_mode:
      name: Husläge
      options:
       - Normal
       - Armed
       - Armed_Home
       - Guest
     time_day:
      name: Time of day
      options:
       - Morning
       - Day
       - Evening
       - Night
     time_year:
       name: Arstid
       options:
        - Summer
        - Winter
        - Autumn
        - Spring
     at_home:
       name: is Home
       options:
        - Home
        - Left
        - Away
        - Extended
     window_lamp:
       name: Window Lamps
       options:
        - _On_
        - _Off_
     show_temps:
       name: Show Temperatures
       options:
        - _On_
        - _Off_
     
automation: !include automation.yaml
binary_sensor: !include binary_sensor.yaml


script: !include scripts.yaml

switch: !include switch.yaml

shell_command:
       genmov:  ffmpeg -r 3 -f image2 -s 640x480 -i /tmp/livingroom%d.jpg /tmp/test.avi
       rmmov: rm -f /tmp/test.avi
       rmjpeg: rm -f /tmp/*jpeg
       zip: cd /tmp && zip images.zip livingroom*.jpg
       shutdown: ssh pi@192.168.0.6 "sudo halt"


mqtt:
  broker: 192.168.0.12
  username: hass
  password: !secret mqtt_pass

zone:
  - name: Home
    latitude: !secret h_lat
    longitude: !secret h_lon
    radius: 450
    icon: mdi:home
  - name: Enter Zone
    latitude: !secret h_lat
    longitude: !secret h_lon
    radius: 700
    icon: mdi:home
  - name: sju
    latitude: !secret sj_lat
    longitude: !secret sj_lon
    radius: 500
    icon: mdi:hospital-building
  - name: veo
    latitude: !secret ve_lat
    longitude: !secret ve_lon
    radius: 500
    icon: mdi:car

input_boolean:  
  notify_debug_l1:
    name: Level 1 Debug
    initial: off
    icon: mdi:car
  notify_debug_l2:
    name: Level 2 Debug
    initial: off
    icon: mdi:car
  notify_debug_l3:
    name: Level 3 Debug
    initial: off
    icon: mdi:car
  wakeup_enabled:
    name: "Wake-up lights"
    initial: on
    icon: mdi:theme-light-dark


input_datetime:
  wakeup_time:
    name: "Vakna vid"
    has_time: true
    has_date: false
    initial: "07:20"
  plant_turn_on:
    name: "Växtlampa På"
    has_time: true
    has_date: false
    initial: "6:00"
  plant_turn_off:
    name: "Växtlampa off"
    has_time: true
    has_date: false
    initial: "06:05"
 
sensor:
  - platform: time_date
    display_options:
     - 'time'
map:


tellduslive:
 host: !secret tells_ip
 scan_interval: 2
