title: Home
views:
  - title: default_view
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Scenes
          - type: conditional
            card:
              entity: alarm_control_panel.alarm
              type: alarm-panel
            conditions:
              - state: Armed
                entity: input_select.hus_mode
          - type: horizontal-stack
            cards:
              - tap_action:
                  action: toggle
                entity: switch.window_lamps
                type: entity-button
                icon: 'mdi:lightbulb-on'
                name: Fönster
              - tap_action:
                  action: call-service
                  service_data:
                    entity_id: script.going_away
                  service: script.turn_on
                entity: script.going_away
                type: entity-button
                icon: 'mdi:exit-run'
                name: Away
              - entity: alarm_control_panel.alarm
                type: entity-button
                icon: 'mdi:shield-key'
                name: Alarm
              - tap_action:
                  action: toggle
                entity: switch.guest_mode
                type: entity-button
                icon: 'mdi:account-multiple'
                name: Gäst
              - tap_action:
                  action: toggle
                entity: switch.show_temp_mode
                type: entity-button
                icon: 'mdi:oil-temperature'
                name: Temps
            name: Scenes
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - graph: line
                  entity: sensor.kok_rorelse_temperature
                  type: sensor
                  name: 'utomhus '
            conditions:
              - state: _On_
                entity: input_select.show_temps
        name: Scenes
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Vardagsrum
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - graph: line
                  entity: sensor.vardagsrum_laddstation_power_2
                  type: sensor
                  icon: 'mdi:battery-charging'
                  name: ' '
                - graph: line
                  entity: sensor.vardagsrum_rorelse_temperature
                  type: sensor
                  name: ' '
                - graph: line
                  entity: sensor.vardagsrum_rorelse_luminance
                  type: sensor
                  name: ' '
            conditions:
              - state: _On_
                entity: input_select.show_temps
          - type: horizontal-stack
            cards:
              - entities:
                  - tap_action:
                      action: toggle
                    entity: switch.vardagsrum_bordslampa
                    icon: 'mdi:lamp'
                    name: Byrå
                  - tap_action:
                      action: toggle
                    entity: switch.vardagsrum_laddstation
                    icon: 'mdi:battery-charging'
                  - tap_action:
                      action: toggle
                    entity: switch.vardagsrum_fonsterlampa
                    icon: 'mdi:window-closed'
                    name: Fönster
                  - tap_action:
                      action: toggle
                    entity: light.altan
                    icon: 'mdi:wall-sconce'
                    name: Altan
                type: glance
        name: Vardagsrum
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Kök
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - graph: line
                  entity: sensor.kok_rorelse_temperature
                  type: sensor
                  name: ' '
                - graph: line
                  entity: sensor.kok_rorelse_luminance
                  type: sensor
                  name: ' '
            conditions:
              - state: _On_
                entity: input_select.show_temps
          - type: horizontal-stack
            cards:
              - entities:
                  - tap_action:
                      action: toggle
                    entity: switch.kaffemaskin
                    icon: 'mdi:coffee'
                  - tap_action:
                      action: toggle
                    entity: switch.kok_fonsterlampa
                    icon: 'mdi:window-closed'
                    name: Fönster
                  - tap_action:
                      action: toggle
                    entity: light.koksbank
                    icon: 'mdi:dishwasher'
                    name: Diskbänk
                type: glance
        name: Kök
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Hall
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - graph: line
                  entity: sensor.hall_rorelsesensor_temperature
                  type: sensor
                  name: ' '
                - graph: line
                  entity: sensor.hall_rorelsesensor_luminance
                  type: sensor
                  name: ' '
            conditions:
              - state: _On_
                entity: input_select.show_temps
          - type: horizontal-stack
            cards:
              - entities:
                  - tap_action:
                      action: toggle
                    entity: switch.hall_trapplampa
                    icon: 'mdi:lamp'
                type: glance
        name: Kök
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Sovrum
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - graph: line
                  entity: sensor.sovrum_humidity
                  type: sensor
                  name: ' '
                - graph: line
                  entity: sensor.sovrum_temperature
                  type: sensor
                  name: ' '
            conditions:
              - state: _On_
                entity: input_select.show_temps
          - type: conditional
            card:
              entities:
                - entity: input_boolean.wakeup_enabled
                - entity: input_datetime.wakeup_time
              type: entities
            conditions:
              - state: Evening
                entity: input_select.time_day
          - type: conditional
            card:
              entities:
                - entity: input_boolean.wakeup_enabled
                - entity: input_datetime.wakeup_time
              type: entities
            conditions:
              - state: Night
                entity: input_select.time_day
          - type: horizontal-stack
            cards:
              - type: markdown
                content: |
                  ## Dorothea
              - type: markdown
                content: |
                  ## Kristian
          - type: horizontal-stack
            cards:
              - entities:
                  - tap_action:
                      action: toggle
                    entity: light.dorotheas_sanglampa
                    icon: 'mdi:human-female'
                    name: lampa
                  - tap_action:
                      action: toggle
                    entity: switch.mobilladdare_dorothea
                    icon: 'mdi:battery-charging'
                    name: laddare
                type: glance
              - entities:
                  - tap_action:
                      action: toggle
                    entity: light.kristians_sanglampa
                    icon: 'mdi:human'
                    name: lampa
                  - tap_action:
                      action: toggle
                    entity: switch.mobilladdare_kristian
                    icon: 'mdi:battery-charging'
                    name: laddare
                type: glance
        name: Vardagsrum
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Förråd
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - graph: line
                  entity: sensor.forrad_humidity
                  type: sensor
                  name: ' '
                - graph: line
                  entity: sensor.forrad_temperature
                  type: sensor
                  name: ' '
                - graph: line
                  entity: sensor.forradsfrys_temperature
                  type: sensor
                  name: ' '
            conditions:
              - state: _On_
                entity: input_select.show_temps
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - entities:
                    - tap_action:
                        action: toggle
                      entity: switch.forrad_uttag
                      icon: 'mdi:radiator'
                      name: Element
                  type: glance
            conditions:
              - state: Winter
                entity: input_select.time_year
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - entities:
                    - tap_action:
                        action: toggle
                      entity: switch.forrad_uttag
                      icon: 'mdi:bike'
                      name: Cykelladdare
                  type: glance
            conditions:
              - state: Summer
                entity: input_select.time_year
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - entities:
                    - tap_action:
                        action: toggle
                      entity: switch.forrad_uttag
                      icon: 'mdi:bike'
                      name: Cykelladdare
                  type: glance
            conditions:
              - state: Autumn
                entity: input_select.time_year
          - type: conditional
            card:
              type: horizontal-stack
              cards:
                - entities:
                    - tap_action:
                        action: toggle
                      entity: switch.forrad_uttag
                      icon: 'mdi:bike'
                      name: Cykelladdare
                  type: glance
            conditions:
              - state: Spring
                entity: input_select.time_year
        name: Arbetsrum
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Korridor
          - type: horizontal-stack
            cards:
              - entities:
                  - tap_action:
                      action: toggle
                    entity: light.korridor_fonsterlampa
                    icon: 'mdi:lamp'
                type: glance
        name: Kök
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Syrum
          - type: horizontal-stack
            cards:
              - entities:
                  - tap_action:
                      action: toggle
                    entity: switch.syrum_fonsterlampa
                    icon: 'mdi:lamp'
                type: glance
        name: Syrum
    badges: []
    panel: false
    icon: 'mdi:home'
    path: default_view
  - icon: 'mdi:airplay'
    cards:
      - type: vertical-stack
        cards:
          - entity: media_player.vardagsrum
            type: media-control
          - type: horizontal-stack
            cards:
              - tap_action:
                  action: toggle
                entity: switch.tv_vol_up
                type: entity-button
                icon: 'mdi:volume-plus'
                name: ' '
              - tap_action:
                  action: toggle
                entity: switch.tv_ch_up
                type: entity-button
                icon: 'mdi:chevron-up-circle'
                name: ' '
              - tap_action:
                  action: toggle
                entity: switch.tv_phillips_on
                type: entity-button
                icon: 'mdi:power'
                name: ' '
          - type: horizontal-stack
            cards:
              - tap_action:
                  action: toggle
                entity: switch.tv_phillips_mute
                type: entity-button
                icon: 'mdi:square-small'
                name: ' '
              - tap_action:
                  action: toggle
                entity: switch.tv_phillips_mute
                type: entity-button
                icon: 'mdi:volume-off'
                name: ' '
              - tap_action:
                  action: toggle
                entity: switch.tv_phillips_mute
                type: entity-button
                icon: 'mdi:square-small'
                name: ' '
          - type: horizontal-stack
            cards:
              - tap_action:
                  action: toggle
                entity: switch.tv_vol_down
                type: entity-button
                icon: 'mdi:volume-minus'
                name: ' '
              - tap_action:
                  action: toggle
                entity: switch.tv_ch_down
                type: entity-button
                icon: 'mdi:chevron-down-circle'
                name: ' '
              - tap_action:
                  action: toggle
                entity: switch.tv_ch_down
                type: entity-button
                icon: 'mdi:square-small'
                name: ' '
    badges: []
    path: tv_view
    title: Tv
  - title: Plants
    icon: 'mdi:flower'
    badges: []
    cards:
      - tap_action:
          action: more-info
        entity: input_datetime.plant_turn_on
        type: entity-button
        hold_action:
          action: none
        name: På
  - title: Survailance
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Home
          - type: conditional
            card:
              entity: alarm_control_panel.alarm
              type: alarm-panel
            conditions:
              - state: Armed
                entity: input_select.hus_mode
          - type: horizontal-stack
            cards:
              - camera_image: camera.livingroom
                entities: []
                type: picture-glance
                title: Livingroom
              - camera_image: camera.raspberry_pi_camera
                entities:
                  - binary_sensor.altan_break
                type: picture-glance
                title: Livingroom
          - type: horizontal-stack
            cards:
              - entity: binary_sensor.motion
                type: entity-button
              - entity: binary_sensor.fire_alarm
                type: entity-button
              - entity: binary_sensor.at_home
                type: entity-button
          - entities:
              - entity: binary_sensor.hall_rorelsesensor
                icon: 'mdi:shoe-formal'
                name: ''
              - entity: binary_sensor.kok_rorelse
                icon: 'mdi:pot'
                name: ''
              - entity: binary_sensor.vardagsrum_rorelse
                icon: 'mdi:television-classic'
                name: ''
              - entity: binary_sensor.work_motion
                icon: 'mdi:hammer'
                name: ''
              - entity: binary_sensor.altan_motion
                icon: 'mdi:umbrella'
                name: ''
            type: glance
            title: null
      - entities:
          - binary_sensor.fire_alarm
          - binary_sensor.kristian_collect
          - binary_sensor.dorothea_collect
          - binary_sensor.at_home
        type: entities
        title: Integrity
        show_header_toggle: true
      - entities:
          - binary_sensor.motion
          - binary_sensor.korridor_motion
          - binary_sensor.hall_rorelsesensor
          - binary_sensor.kok_rorelse
          - binary_sensor.vardagsrum_rorelse
          - binary_sensor.work_motion
          - binary_sensor.altan_motion
        type: entities
        title: Motion
        show_header_toggle: true
      - entities:
          - binary_sensor.hall_break
          - binary_sensor.altan_break
          - binary_sensor.work_break
        type: entities
        title: Doors
        show_header_toggle: true
    badges: []
    panel: true
    icon: 'mdi:camera'
    path: motion_view
  - icon: 'mdi:account-multiple'
    cards:
      - entities:
          - automation.winter_element_workroom_off
          - automation.winter_element_workroom
          - automation.charger_workroom_off
          - script.signal_alarm_active
        type: entities
        title: Charger or element
        show_header_toggle: true
      - entities:
          - automation.bedroom_charging_evening_on
          - automation.charger_off_controller
          - automation.evening_light_on
          - automation.evening_light_off
          - automation.turnofftv
          - automation.turnonkitchen
          - automation.morning_light_on
          - automation.morninglight_off
        type: entities
        title: Automation
      - entities:
          - input_boolean.notify_debug_l1
          - input_boolean.notify_debug_l2
          - input_boolean.notify_debug_l3
        type: entities
        title: Välj av eller på
      - entities:
          - input_select.window_lamp
          - input_select.hus_mode
          - input_select.time_day
          - input_select.time_year
          - input_select.at_home
        type: entities
        title: Välj
      - entities:
          - script.temp_flash_015
          - script.temp_flash_10
          - script.temp_flash_5
          - script.temp_flash_0
          - script.temp_flash_05
          - script.temp_flash_010
          - script.alarm_sequence
          - script.armed_notification
          - script.windowlamps_off
          - script.windowlamps_on
          - script.shutdown
        type: entities
        title: Skript
      - entities:
          - switch.fire_alam_off
        type: entities
        title: Kontakt
    badges:
      - device_tracker.kristian
      - device_tracker.hass_kr
      - device_tracker.dorothea
      - device_tracker.hass_dotti
    path: automation_view
    title: Automations
