title: Home
views:
  - icon: 'mdi:home'
    path: default_view
    title: default_view
    cards:
      - cards:
          - content: |
              ## Scenes
            type: markdown
          - type: conditional
            card:
              entity: alarm_control_panel.alarm
              type: alarm-panel
            conditions:
              - entity: input_select.hus_mode
                state: Armed
          - cards:
              - entity: switch.window_lamps
                tap_action:
                  action: toggle
                name: Fönster
                icon: 'mdi:lightbulb-on'
                type: entity-button
              - entity: script.going_away
                tap_action:
                  service_data:
                    entity_id: script.going_away
                  action: call-service
                  service: script.turn_on
                name: Away
                icon: 'mdi:exit-run'
                type: entity-button
              - entity: alarm_control_panel.alarm
                name: Alarm
                icon: 'mdi:shield-key'
                type: entity-button
              - entity: switch.guest_mode
                tap_action:
                  action: toggle
                name: Gäst
                icon: 'mdi:account-multiple'
                type: entity-button
              - entity: switch.show_temp_mode
                tap_action:
                  action: toggle
                name: Temps
                icon: 'mdi:oil-temperature'
                type: entity-button
            type: horizontal-stack
            name: Scenes
          - type: conditional
            card:
              cards:
                - entity: sensor.utomhus_temperature
                  name: 'utomhus '
                  graph: line
                  type: sensor
              type: horizontal-stack
            conditions:
              - entity: input_select.show_temps
                state: _On_
        type: vertical-stack
        name: Scenes
      - cards:
          - content: |
              ## Vardagsrum
            type: markdown
          - type: conditional
            card:
              cards:
                - entity: sensor.vardagsrum_laddstation_power_2
                  name: ' '
                  graph: line
                  type: sensor
                  icon: 'mdi:battery-charging'
                - entity: sensor.vardagsrum_rorelse_temperature
                  name: ' '
                  graph: line
                  type: sensor
                - entity: sensor.vardagsrum_rorelse_luminance
                  name: ' '
                  graph: line
                  type: sensor
              type: horizontal-stack
            conditions:
              - entity: input_select.show_temps
                state: _On_
          - cards:
              - type: glance
                entities:
                  - entity: switch.vardagsrum_bordslampa
                    tap_action:
                      action: toggle
                    name: Byrå
                    icon: 'mdi:lamp'
                  - entity: switch.vardagsrum_laddstation
                    tap_action:
                      action: toggle
                    icon: 'mdi:battery-charging'
                  - entity: switch.vardagsrum_fonsterlampa
                    tap_action:
                      action: toggle
                    name: Fönster
                    icon: 'mdi:window-closed'
                  - entity: light.altan
                    tap_action:
                      action: toggle
                    name: Altan
                    icon: 'mdi:wall-sconce'
            type: horizontal-stack
        type: vertical-stack
        name: Vardagsrum
      - cards:
          - content: |
              ## Kök
            type: markdown
          - type: conditional
            card:
              cards:
                - entity: sensor.kok_rorelse_temperature
                  name: ' '
                  graph: line
                  type: sensor
                - entity: sensor.kok_rorelse_luminance
                  name: ' '
                  graph: line
                  type: sensor
              type: horizontal-stack
            conditions:
              - entity: input_select.show_temps
                state: _On_
          - cards:
              - type: glance
                entities:
                  - entity: switch.kaffemaskin
                    tap_action:
                      action: toggle
                    icon: 'mdi:coffee'
                  - entity: switch.kok_fonsterlampa
                    tap_action:
                      action: toggle
                    name: Fönster
                    icon: 'mdi:window-closed'
                  - entity: light.koksbank
                    tap_action:
                      action: toggle
                    name: Diskbänk
                    icon: 'mdi:dishwasher'
            type: horizontal-stack
        type: vertical-stack
        name: Kök
      - cards:
          - content: |
              ## Hall
            type: markdown
          - type: conditional
            card:
              cards:
                - entity: sensor.hall_rorelsesensor_temperature
                  name: ' '
                  graph: line
                  type: sensor
                - entity: sensor.hall_rorelsesensor_luminance
                  name: ' '
                  graph: line
                  type: sensor
              type: horizontal-stack
            conditions:
              - entity: input_select.show_temps
                state: _On_
          - cards:
              - type: glance
                entities:
                  - entity: switch.hall_trapplampa
                    tap_action:
                      action: toggle
                    icon: 'mdi:lamp'
            type: horizontal-stack
        type: vertical-stack
        name: Kök
      - cards:
          - content: |
              ## Sovrum
            type: markdown
          - type: conditional
            card:
              cards:
                - entity: sensor.sovrum_humidity
                  name: ' '
                  graph: line
                  type: sensor
                - entity: sensor.sovrum_temperature
                  name: ' '
                  graph: line
                  type: sensor
              type: horizontal-stack
            conditions:
              - entity: input_select.show_temps
                state: _On_
          - type: conditional
            card:
              type: entities
              entities:
                - entity: input_boolean.wakeup_enabled
                - entity: input_datetime.wakeup_time
            conditions:
              - entity: input_select.time_day
                state: Evening
          - type: conditional
            card:
              type: entities
              entities:
                - entity: input_boolean.wakeup_enabled
                - entity: input_datetime.wakeup_time
            conditions:
              - entity: input_select.time_day
                state: Night
          - cards:
              - content: |
                  ## Dorothea
                type: markdown
              - content: |
                  ## Kristian
                type: markdown
            type: horizontal-stack
          - cards:
              - type: glance
                entities:
                  - entity: light.dorotheas_sanglampa
                    tap_action:
                      action: toggle
                    name: lampa
                    icon: 'mdi:human-female'
                  - entity: switch.mobilladdare_dorothea
                    tap_action:
                      action: toggle
                    name: laddare
                    icon: 'mdi:battery-charging'
              - type: glance
                entities:
                  - entity: light.kristians_sanglampa
                    tap_action:
                      action: toggle
                    name: lampa
                    icon: 'mdi:human'
                  - entity: switch.mobilladdare_kristian
                    tap_action:
                      action: toggle
                    name: laddare
                    icon: 'mdi:battery-charging'
            type: horizontal-stack
        type: vertical-stack
        name: Vardagsrum
      - cards:
          - content: |
              ## Förråd
            type: markdown
          - type: conditional
            card:
              cards:
                - entity: sensor.forrad_humidity
                  name: ' '
                  graph: line
                  type: sensor
                - entity: sensor.forrad_temperature
                  name: ' '
                  graph: line
                  type: sensor
                - entity: sensor.forradsfrys_temperature
                  name: ' '
                  graph: line
                  type: sensor
              type: horizontal-stack
            conditions:
              - entity: input_select.show_temps
                state: _On_
          - type: conditional
            card:
              cards:
                - type: glance
                  entities:
                    - entity: switch.forrad_uttag
                      tap_action:
                        action: toggle
                      name: Element
                      icon: 'mdi:radiator'
              type: horizontal-stack
            conditions:
              - entity: input_select.time_year
                state: Winter
          - type: conditional
            card:
              cards:
                - type: glance
                  entities:
                    - entity: switch.forrad_uttag
                      tap_action:
                        action: toggle
                      name: Cykelladdare
                      icon: 'mdi:bike'
              type: horizontal-stack
            conditions:
              - entity: input_select.time_year
                state: Summer
          - type: conditional
            card:
              cards:
                - type: glance
                  entities:
                    - entity: switch.forrad_uttag
                      tap_action:
                        action: toggle
                      name: Cykelladdare
                      icon: 'mdi:bike'
              type: horizontal-stack
            conditions:
              - entity: input_select.time_year
                state: Autumn
          - type: conditional
            card:
              cards:
                - type: glance
                  entities:
                    - entity: switch.forrad_uttag
                      tap_action:
                        action: toggle
                      name: Cykelladdare
                      icon: 'mdi:bike'
              type: horizontal-stack
            conditions:
              - entity: input_select.time_year
                state: Spring
        type: vertical-stack
        name: Arbetsrum
      - cards:
          - content: |
              ## Korridor
            type: markdown
          - cards:
              - type: glance
                entities:
                  - entity: light.korridor_fonsterlampa
                    tap_action:
                      action: toggle
                    icon: 'mdi:lamp'
            type: horizontal-stack
        type: vertical-stack
        name: Kök
      - cards:
          - content: |
              ## Syrum
            type: markdown
          - cards:
              - type: glance
                entities:
                  - entity: switch.syrum_fonsterlampa
                    tap_action:
                      action: toggle
                    icon: 'mdi:lamp'
            type: horizontal-stack
        type: vertical-stack
        name: Syrum
    badges: []
    panel: false
  - cards:
      - cards:
          - entity: media_player.vardagsrum
            type: media-control
          - cards:
              - entity: switch.tv_vol_up
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:volume-plus'
                type: entity-button
              - entity: switch.tv_ch_up
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:chevron-up-circle'
                type: entity-button
              - entity: switch.tv_phillips_on
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:power'
                type: entity-button
            type: horizontal-stack
          - cards:
              - entity: switch.tv_phillips_mute
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:square-small'
                type: entity-button
              - entity: switch.tv_phillips_mute
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:volume-off'
                type: entity-button
              - entity: switch.tv_phillips_mute
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:square-small'
                type: entity-button
            type: horizontal-stack
          - cards:
              - entity: switch.tv_vol_down
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:volume-minus'
                type: entity-button
              - entity: switch.tv_ch_down
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:chevron-down-circle'
                type: entity-button
              - entity: switch.tv_ch_down
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:square-small'
                type: entity-button
            type: horizontal-stack
        type: vertical-stack
    title: Tv
    path: tv_view
    icon: 'mdi:airplay'
    badges: []
  - cards:
      - entity: weather.smhi_home
        type: weather-forecast
      - type: entity-button
        name: På
        icon: 'mdi:flower'
        entity: switch.device_65
        tap_action:
          action: toggle
        hold_action:
          action: more-info
    title: Plants
    icon: 'mdi:flower'
    badges: []
  - icon: 'mdi:camera'
    path: motion_view
    title: Survailance
    cards:
      - cards:
          - content: |
              ## Home
            type: markdown
          - type: conditional
            card:
              entity: alarm_control_panel.alarm
              type: alarm-panel
            conditions:
              - entity: input_select.hus_mode
                state: Armed
          - cards:
              - title: Livingroom
                camera_image: camera.livingroom
                entities: []
                type: picture-glance
              - title: Livingroom
                camera_image: camera.raspberry_pi_camera
                entities:
                  - binary_sensor.altan_break
                type: picture-glance
            type: horizontal-stack
          - cards:
              - entity: binary_sensor.motion
                type: entity-button
              - entity: binary_sensor.fire_alarm
                type: entity-button
              - entity: binary_sensor.at_home
                type: entity-button
            type: horizontal-stack
          - title: null
            type: glance
            entities:
              - entity: binary_sensor.hall_rorelsesensor
                name: ''
                icon: 'mdi:shoe-formal'
              - entity: binary_sensor.kok_rorelse
                name: ''
                icon: 'mdi:pot'
              - entity: binary_sensor.vardagsrum_rorelse
                name: ''
                icon: 'mdi:television-classic'
              - entity: binary_sensor.work_motion
                name: ''
                icon: 'mdi:hammer'
              - entity: binary_sensor.altan_motion
                name: ''
                icon: 'mdi:umbrella'
        type: vertical-stack
      - title: Integrity
        type: entities
        entities:
          - binary_sensor.fire_alarm
          - binary_sensor.kristian_collect
          - binary_sensor.dorothea_collect
          - binary_sensor.at_home
        show_header_toggle: true
      - title: Motion
        type: entities
        entities:
          - binary_sensor.motion
          - binary_sensor.korridor_motion
          - binary_sensor.hall_rorelsesensor
          - binary_sensor.kok_rorelse
          - binary_sensor.vardagsrum_rorelse
          - binary_sensor.work_motion
          - binary_sensor.altan_motion
        show_header_toggle: true
      - title: Doors
        type: entities
        entities:
          - binary_sensor.hall_break
          - binary_sensor.altan_break
          - binary_sensor.work_break
        show_header_toggle: true
    badges: []
    panel: true
  - cards:
      - title: Charger or element
        type: entities
        entities:
          - automation.winter_element_workroom_off
          - automation.winter_element_workroom
          - automation.charger_workroom_off
          - script.signal_alarm_active
        show_header_toggle: true
      - title: Automation
        type: entities
        entities:
          - automation.bedroom_charging_evening_on
          - automation.charger_off_controller
          - automation.evening_light_on
          - automation.evening_light_off
          - automation.turnofftv
          - automation.turnonkitchen
          - automation.morning_light_on
          - automation.morninglight_off
      - title: Välj av eller på
        type: entities
        entities:
          - input_boolean.notify_debug_l1
          - input_boolean.notify_debug_l2
          - input_boolean.notify_debug_l3
      - title: Välj
        type: entities
        entities:
          - input_select.window_lamp
          - input_select.hus_mode
          - input_select.time_day
          - input_select.time_year
          - input_select.at_home
      - title: Skript
        type: entities
        entities:
          - script.temp_flash_015
          - script.temp_flash_10
          - script.temp_flash_5
          - script.temp_flash_0
          - script.temp_flash_05
          - script.temp_flash_010
          - script.alarm_sequence
          - script.armed_notification
          - script.windowlamps_off
          - script.windowlamps_on
          - script.shutdown
      - title: Kontakt
        type: entities
        entities:
          - switch.fire_alam_off
    title: Automations
    path: automation_view
    icon: 'mdi:account-multiple'
    badges:
      - device_tracker.kristian
      - device_tracker.hass_kr
      - device_tracker.dorothea
      - device_tracker.hass_dotti
