title: Home
views:
  - badges: []
    icon: 'mdi:home'
    panel: false
    cards:
      - type: vertical-stack
        cards:
                - type: vertical-stack
                  name: Scenes
                  cards:
                    - type: markdown
                      content: |
                        ## Scenes
                    - type: conditional
                      conditions:
                        - entity: input_select.hus_mode
                          state: Armed
                      card:
                        type: alarm-panel
                        entity: alarm_control_panel.alarm
                    - type: horizontal-stack
                      name: Scenes
                      cards:
                        - type: entity-button
                          tap_action:
                            action: toggle
                          name: Fönster
                          icon: 'mdi:lightbulb-on'
                          entity: switch.window_lamps
                        - type: entity-button
                          tap_action:
                            action: call-service
                            service: script.turn_on
                            service_data:
                              entity_id: script.going_away
                          name: Away
                          icon: 'mdi:exit-run'
                          entity: script.going_away
                        - type: entity-button
                          icon: 'mdi:shield-key'
                          entity: alarm_control_panel.alarm
                          name: Alarm
                        - type: entity-button
                          tap_action:
                            action: toggle
                          name: Gäst
                          icon: 'mdi:account-multiple'
                          entity: switch.guest_mode
                        - type: entity-button
                          tap_action:
                            action: toggle
                          name: Temps
                          icon: 'mdi:oil-temperature'
                          entity: switch.show_temp_mode
                - type: vertical-stack
                  name: Vardagsrum
                  cards:
                    - type: markdown
                      content: |
                        ## Vardagsrum
                    - type: conditional
                      conditions:
                        - entity: input_select.show_temps
                          state: _On_
                      card:
                        type: horizontal-stack
                        cards:
                          - type: sensor
                            graph: line
                            icon: 'mdi:battery-charging'
                            entity: sensor.vardagsrum_laddstation_power_2
                            name: ' '
                          - type: sensor
                            graph: line
                            entity: sensor.vardagsrum_rorelse_temperature
                            name: ' '
                          - type: sensor
                            graph: line
                            entity: sensor.vardagsrum_rorelse_luminance
                            name: ' '
                    - type: horizontal-stack
                      cards:
                        - type: glance
                          entities:
                            - entity: switch.vardagsrum_bordslampa
                              tap_action:
                                action: toggle
                              name: Byrå
                              icon: 'mdi:lamp'
                            - entity: switch.vardagsrum_laddstation
                              tap_action:
                                action: toggle
                              icon: 'mdi:battery-charging'
                            - entity: switch.vardagsrum_fonsterlampa
                              tap_action:
                                action: toggle
                              name: Fönster
                              icon: 'mdi:window-closed'
                            - entity: light.altan
                              tap_action:
                                action: toggle
                              name: Altan
                              icon: 'mdi:wall-sconce'
                - type: vertical-stack
                  name: Kök
                  cards:
                    - type: markdown
                      content: |
                        ## Kök
                    - type: conditional
                      conditions:
                        - entity: input_select.show_temps
                          state: _On_
                      card:
                        type: horizontal-stack
                        cards:
                          - type: sensor
                            graph: line
                            entity: sensor.kok_rorelse_temperature
                            name: ' '
                          - type: sensor
                            graph: line
                            entity: sensor.kok_rorelse_luminance
                            name: ' '
                    - type: horizontal-stack
                      cards:
                        - type: glance
                          entities:
                            - entity: switch.kaffemaskin
                              tap_action:
                                action: toggle
                              icon: 'mdi:coffee'
                            - entity: switch.kok_fonsterlampa
                              tap_action:
                                action: toggle
                              name: Fönster
                              icon: 'mdi:window-closed'
                - type: vertical-stack
                  name: Kök
                  cards:
                    - type: markdown
                      content: |
                        ## Hall
                    - type: conditional
                      conditions:
                        - entity: input_select.show_temps
                          state: _On_
                      card:
                        type: horizontal-stack
                        cards:
                          - type: sensor
                            graph: line
                            entity: sensor.hall_rorelsesensor_temperature
                            name: ' '
                          - type: sensor
                            graph: line
                            entity: sensor.hall_rorelsesensor_luminance
                            name: ' '
                    - type: horizontal-stack
                      cards:
                        - type: glance
                          entities:
                            - entity: switch.hall_trapplampa
                              tap_action:
                                action: toggle
                              icon: 'mdi:lamp'
                - type: vertical-stack
                  name: Vardagsrum
                  cards:
                    - type: markdown
                      content: |
                        ## Sovrum
                    - type: conditional
                      conditions:
                        - entity: input_select.show_temps
                          state: _On_
                      card:
                        type: horizontal-stack
                        cards:
                          - type: sensor
                            graph: line
                            entity: sensor.sovrum_humidity
                            name: ' '
                          - type: sensor
                            graph: line
                            entity: sensor.sovrum_temperature
                            name: ' '
                    - type: conditional
                      conditions:
                        - entity: input_select.time_day
                          state: Evening
                      card:
                        type: entities
                        entities:
                          - entity: input_boolean.wakeup_enabled
                          - entity: input_datetime.wakeup_time
                    - type: conditional
                      conditions:
                        - entity: input_select.time_day
                          state: Night
                      card:
                        type: entities
                        entities:
                          - entity: input_boolean.wakeup_enabled
                          - entity: input_datetime.wakeup_time
                    - type: horizontal-stack
                      cards:
                        - type: markdown
                          content: |
                            ## Dorothea
                        - type: markdown
                          content: |
                            ## Kristian
                    - type: horizontal-stack
                      cards:
                        - type: glance
                          entities:
                            - entity: light.dorotheas_sanglampa
                              tap_action:
                                action: toggle
                              name: lampa
                              icon: 'mdi:human-female'
                            - entity: switch.mobilladdare_dorothea
                              tap_action:
                                action: toggle
                              name: laddare
                              icon: 'mdi:battery-charging'
                        - type: glance
                          entities:
                            - entity: light.kristians_sanglampa
                              tap_action:
                                action: toggle
                              name: lampa
                              icon: 'mdi:human'
                            - entity: switch.mobilladdare_kristian
                              tap_action:
                                action: toggle
                              name: laddare
                              icon: 'mdi:battery-charging'
                - type: vertical-stack
                  name: Arbetsrum
                  cards:
                    - type: markdown
                      content: |
                        ## Förråd
                    - type: conditional
                      conditions:
                        - entity: input_select.show_temps
                          state: _On_
                      card:
                        type: horizontal-stack
                        cards:
                          - type: sensor
                            graph: line
                            entity: sensor.forrad_humidity
                            name: ' '
                          - type: sensor
                            graph: line
                            entity: sensor.forrad_temperature
                            name: ' '
                          - type: sensor
                            graph: line
                            entity: sensor.forradsfrys_temperature
                            name: ' '
                    - type: horizontal-stack
                      cards:
                        - type: glance
                          entities:
                            - entity: switch.forrad_uttag
                              tap_action:
                                action: toggle
                              name: element
                              icon: 'mdi:radiator'
                - type: vertical-stack
                  name: Kök
                  cards:
                    - type: markdown
                      content: |
                        ## Korridor
                    - type: horizontal-stack
                      cards:
                        - type: glance
                          entities:
                            - entity: light.korridor_fonsterlampa
                              tap_action:
                                action: toggle
                              icon: 'mdi:lamp'
                - type: vertical-stack
                  name: Syrum
                  cards:
                    - type: markdown
                      content: |
                        ## Syrum
                    - type: horizontal-stack
                      cards:
                        - type: glance
                          entities:
                            - entity: switch.syrum_fonsterlampa
                              tap_action:
                                action: toggle
                              icon: 'mdi:lamp'
    title: default_view
    path: default_view
  - badges: []
    icon: 'mdi:airplay'
    title: Tv
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.vardagsrum
          - type: horizontal-stack
            cards:
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:volume-plus'
                entity: switch.tv_vol_up
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:chevron-up-circle'
                entity: switch.tv_ch_up
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:power'
                entity: switch.tv_phillips_on
          - type: horizontal-stack
            cards:
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:square-small'
                entity: switch.tv_phillips_mute
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:volume-off'
                entity: switch.tv_phillips_mute
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:square-small'
                entity: switch.tv_phillips_mute
          - type: horizontal-stack
            cards:
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:volume-minus'
                entity: switch.tv_vol_down
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:chevron-down-circle'
                entity: switch.tv_ch_down
              - type: entity-button
                tap_action:
                  action: toggle
                name: ' '
                icon: 'mdi:square-small'
                entity: switch.tv_ch_down
    path: tv_view
  - badges: []
    icon: 'mdi:camera'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Home
          - type: conditional
            conditions:
              - entity: input_select.hus_mode
                state: Armed
            card:
              type: alarm-panel
              entity: alarm_control_panel.alarm
          - type: horizontal-stack
            cards:
              - type: picture-glance
                camera_image: camera.livingroom
                entities: []
                title: Livingroom
              - type: picture-glance
                camera_image: camera.raspberry_pi_camera
                entities:
                  - binary_sensor.altan_break
                title: Livingroom
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: binary_sensor.motion
              - type: entity-button
                entity: binary_sensor.fire_alarm
              - type: entity-button
                entity: binary_sensor.at_home
          - type: glance
            entities:
              - icon: 'mdi:shoe-formal'
                entity: binary_sensor.hall_rorelsesensor
                name: ''
              - icon: 'mdi:pot'
                entity: binary_sensor.kok_rorelse
                name: ''
              - icon: 'mdi:television-classic'
                entity: binary_sensor.vardagsrum_rorelse
                name: ''
              - icon: 'mdi:hammer'
                entity: binary_sensor.work_motion
                name: ''
              - icon: 'mdi:umbrella'
                entity: binary_sensor.altan_motion
                name: ''
            title: null
      - type: entities
        entities:
          - binary_sensor.fire_alarm
          - binary_sensor.kristian_collect
          - binary_sensor.dorothea_collect
          - binary_sensor.at_home
        show_header_toggle: true
        title: Integrity
      - type: entities
        entities:
          - binary_sensor.motion
          - binary_sensor.korridor_motion
          - binary_sensor.hall_rorelsesensor
          - binary_sensor.kok_rorelse
          - binary_sensor.vardagsrum_rorelse
          - binary_sensor.work_motion
          - binary_sensor.altan_motion
        show_header_toggle: true
        title: Motion
      - type: entities
        entities:
          - binary_sensor.hall_break
          - binary_sensor.altan_break
          - binary_sensor.work_break
        show_header_toggle: true
        title: Doors
    title: Survailance
    path: motion_view
  - badges:
      - device_tracker.kristian
      - device_tracker.hass_kr
      - device_tracker.dorothea
      - device_tracker.hass_dotti
    icon: 'mdi:account-multiple'
    title: Automations
    cards:
      - type: entities
        entities:
          - automation.winter_element_workroom_off
          - automation.winter_element_workroom
          - automation.charger_workroom_off
          - script.signal_alarm_active
        show_header_toggle: true
        title: Charger or element
      - type: entities
        entities:
          - automation.bedroom_charging_evening_on
          - automation.charger_off_controller
          - automation.evening_light_on
          - automation.evening_light_off
          - automation.turnofftv
          - automation.turnonkitchen
          - automation.morning_light_on
          - automation.morninglight_off
        title: Automation
      - type: entities
        entities:
          - input_boolean.notify_debug_l1
          - input_boolean.notify_debug_l2
          - input_boolean.notify_debug_l3
        title: Välj av eller på
      - type: entities
        entities:
          - input_select.window_lamp
          - input_select.hus_mode
          - input_select.time_day
          - input_select.time_year
          - input_select.at_home
        title: Välj
      - type: entities
        entities:
          - script.temp_flash_015
          - script.temp_flash_10
          - script.temp_flash_5
          - script.temp_flash_0
          - script.temp_flash_05
          - script.temp_flash_010
          - script.alarm_sequence
          - script.armed_notification
          - script.windowlamps_off
          - script.windowlamps_on
          - script.shutdown
        title: Skript
      - type: entities
        entities:
          - switch.fire_alam_off
        title: Kontakt
    path: automation_view
